services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # The database port should not be exposed to the host machine for security reasons.
    # The 'app' service can access it through the internal 'goooo_network'.
    networks:
      - goooo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Go Telegram Bot Application
  app:
    image: go-bot:${IMAGE_TAG:-current}
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080" # Expose app port only to the host for Nginx
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - goooo_network

  # Go Migrate service for database migrations
  migrate:
    image: migrate/migrate:v4.17.1
    profiles:
      - tools
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - goooo_network
    env_file:
      - .env

    healthcheck:
      # This healthcheck now correctly uses wget (installed in the custom Dockerfile)
      # and points to the actual health endpoint proxied by Nginx.
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  goooo_network:
    driver: bridge 
